# Creative Prompt Generator Developed By Kirklen Allen

prompts = {
    "Story Ideas": [
        "A scientist discovers a parallel universe while experimenting with quantum particles.",
        "What if humanity’s survival depended on colonizing a sentient planet?",
        "Write a story about an AI assistant that starts making its own decisions.",
        "Imagine a world where time travel tourism becomes a booming industry.",
        "An intergalactic ambassador must negotiate peace between two rival species.",
        "A forgotten satellite sends mysterious messages back to Earth after decades.",
        "The last human alive encounters a robotic society thriving on Earth.",
        "In a distant future, humans develop the ability to upload their consciousness to stars.",
        "A crew aboard a spaceship discovers an artifact that can manipulate gravity.",
        "Two rival space explorers compete to find the secrets of a lost alien civilization.",
        "A botanist creates a plant capable of terraforming Mars, but it evolves rapidly.",
        "An experimental spaceship powered by black holes malfunctions during a critical mission.",
        "A stranded astronaut must communicate using the planet’s alien lifeforms.",
        "A device that can rewrite memories causes chaos among the elite.",
        "The moon mysteriously vanishes, disrupting Earth's natural rhythms.",
        "A teenager invents a gadget to decode the universal language of the cosmos.",
        "Scientists discover an ancient alien library buried beneath the Antarctic ice.",
        "A city in the clouds hides the secret to a new energy source.",
        "Humanity is contacted by an alien race that only communicates through music.",
        "A group of rebels uses advanced holograms to fight against an oppressive regime.",
        "Earth receives a blueprint for a starship from an unknown source in space.",
        "A device allows people to live in simulated realities, but at a cost.",
        "A team of explorers finds a wormhole that leads to an alternate Earth.",
        "A robot gains sentience and begins questioning its purpose in society.",
        "Humanity builds a Dyson sphere, but something is already living inside it.",
        "A future where individuals can customize their DNA for a perfect life.",
        "Space colonists face challenges on a water-based planet with intelligent marine life.",
        "A young programmer accidentally creates a virtual reality with its own rules.",
        "The first human-alien hybrid struggles with identity and belonging.",
        "A scientist's experiment to stop aging goes terribly wrong, reshaping humanity.",
        "The sun begins emitting a new kind of energy, altering life on Earth.",
        "An ancient spacecraft is discovered hidden beneath a desert.",
        "Scientists unlock the ability to fold space and travel instantaneously.",
        "An astronaut's body begins adapting to zero gravity in unpredictable ways.",
        "A holographic artist creates masterpieces that reveal hidden truths.",
        "A new material absorbs light, but its properties defy explanation.",
        "The galaxy's most dangerous criminal is a master of disguise.",
        "Earth is unknowingly part of a galactic simulation.",
        "A spaceship crew encounters a sentient nebula with its own agenda.",
        "A colony on Mars discovers signs of a long-extinct alien species.",
        "Scientists invent a machine that predicts the next technological breakthrough.",
        "A battle ensues over control of a resource that powers faster-than-light travel.",
        "Humanity builds a ringworld, but it houses a dark secret.",
        "An archaeologist uncovers a device that holds the knowledge of the stars.",
        "The first human-animal hybrids are sent to colonize Venus.",
        "An inventor’s neural interface connects people’s minds but introduces chaos.",
        "A character discovers their memories belong to someone else.",
        "A future where robots write novels better than humans ever could.",
        "The universe’s oldest known species reaches out to teach humanity their ways."
    ],
    "Artwork Inspiration": [
        "Sketch a futuristic city built on floating platforms above the ocean.",
        "Design a spacecraft inspired by marine life.",
        "Create a scene depicting humanity’s first contact with an alien species.",
        "Illustrate a solar farm on Mercury harvesting the sun’s energy.",
        "Conceptualize a character with a biomechanical exosuit powered by nanotechnology.",
        "Visualize a bustling marketplace on a distant planet.",
        "Design a zero-gravity sport played aboard a massive spaceship.",
        "Draw an alien species that evolved with crystalline bodies.",
        "Imagine and create a futuristic robot designed to protect Earth’s ecosystems.",
        "Design an alien tree that grows by absorbing starlight.",
        "Paint an asteroid mining colony on the edge of a distant galaxy.",
        "Create a depiction of Earth as seen from a neighboring galaxy.",
        "Illustrate the first human base on Europa under the icy crust.",
        "Sketch a city built inside the rings of Saturn.",
        "Visualize a spacecraft powered by a miniature black hole.",
        "Draw a planet with three suns and unique ecosystems.",
        "Design a wearable device that blends fashion and technology.",
        "Illustrate an intergalactic council chamber where species gather.",
        "Paint a vision of a utopian society where AI and humans coexist.",
        "Create a cosmic map showing the major trade routes between galaxies.",
        "Imagine a futuristic farm that uses drones and advanced hydroponics.",
        "Visualize an alien species that communicates through color patterns.",
        "Illustrate a space elevator stretching from Earth into orbit.",
        "Conceptualize a futuristic metropolis thriving on renewable energy.",
        "Create an image of a spaceship exploring the heart of a nebula.",
        "Design a character from a civilization living on a tidally locked planet.",
        "Draw a futuristic laboratory where scientists manipulate DNA holographically.",
        "Create an artwork showing the collision of two galaxies.",
        "Illustrate a cybernetic arm designed for deep-space engineering.",
        "Visualize a supercomputer housed in an alien structure.",
        "Paint a panoramic view of an alien moon during an eclipse.",
        "Design an orbital habitat for humanity's distant future.",
        "Draw a futuristic marketplace with alien and human vendors.",
        "Illustrate an intelligent robot farming colony.",
        "Sketch a hover vehicle for exploring gas giant planets.",
        "Visualize a communication beacon left by an ancient alien race.",
        "Design an explorer's suit for navigating black holes.",
        "Paint an alien jungle with bioluminescent plants.",
        "Create an image of a drone repairing a massive spaceship in orbit.",
        "Sketch a scene of a futuristic space museum.",
        "Visualize a zero-gravity dance performance aboard a spaceship.",
        "Design a starship capable of self-repair and evolution.",
        "Create a robotic pet with a unique personality.",
        "Illustrate a high-tech observatory built on a remote alien planet.",
        "Draw a mining operation extracting resources from a comet.",
        "Sketch a futuristic city underwater with domed living spaces.",
        "Imagine a vehicle built to explore the center of a star.",
        "Paint a scene of a galactic celebration with multiple alien cultures."
    ],
    "Personal Challenges": [
        "Design a space exploration game in a week.",
        "Write 1,000 words every day for a month about life in the future.",
        "Learn to 3D model and create a futuristic object.",
        "Spend a day observing technology around you and write about its evolution.",
        "Develop a vision board for technological advancements you’d like to see.",
        "Research and present your thoughts on a major sci-fi movie.",
        "Try writing a short sci-fi screenplay in a week.",
        "Build a model spaceship using everyday materials.",
        "Challenge yourself to learn the basics of astronomy.",
        "Create a short story about your own space exploration journey.",
        "Spend a week sketching one idea for a futuristic invention daily.",
        "Build a diorama of a futuristic city using recycled materials.",
        "Write a diary entry from the perspective of someone living on Mars.",
        "Create a playlist that inspires you to think about the future.",
        "Learn how to code and design a basic game prototype.",
        "Try to create your own alien language, complete with a short dictionary.",
        "Write a poem inspired by the vastness of space.",
        "Challenge yourself to create a 3D-printed model of a sci-fi object.",
        "Spend a day imagining how humans will travel in 500 years and write about it.",
        "Host a discussion about the ethical use of artificial intelligence.",
        "Draw a timeline of major events you’d like to see in humanity’s future.",
        "Learn the basics of electronics and build a small robot or gadget.",
        "Write a fanfiction piece based on your favorite sci-fi movie or book.",
        "Spend an evening stargazing and writing down your thoughts.",
        "Create a time capsule of your favorite technologies to open in 10 years.",
        "Design a sci-fi board game and write out its rules.",
        "Write about how humans would adapt to life without sunlight.",
        "Attempt to sculpt an alien figure using clay or another medium.",
        "Create a futuristic map of Earth after 1,000 years of climate change.",
        "Learn to animate and make a short clip based on a space theme.",
        "Spend a week reading classic sci-fi books and write reviews for each.",
        "Invent and draw a futuristic tool you'd use in space.",
        "Research the International Space Station and write an essay about it.",
        "Create a series of 10 digital artworks inspired by technology.",
        "Challenge yourself to avoid any modern technology for a day.",
        "Write a letter to the first human to land on another planet.",
        "Develop a fictional timeline of humanity's colonization of the stars.",
        "Learn about quantum physics and summarize it for a beginner in your own words.",
        "Organize a debate with friends about the pros and cons of space colonization.",
        "Create a short animation about an alien exploring Earth.",
        "Write a speculative essay about what the Internet will look like in 100 years.",
        "Draw a comic strip about a robot learning to be human.",
        "Design a spacesuit that includes futuristic survival tools.",
        "Write a children’s story about a kid’s adventure on a starship.",
        "Learn the basics of photography and create a sci-fi-inspired photo series.",
        "Write an argument for or against building settlements on the Moon.",
        "Create a flowchart showing how interstellar travel could work.",
        "Design a miniature sci-fi-themed board game with dice or cards.",
        "Spend a weekend creating a piece of wearable tech using craft supplies.",
        "Write a guidebook for travelers visiting a fictional alien planet.",
        "Create a recipe for futuristic food using modern ingredients.",
        "Learn about space telescopes and design one of your own.",
        "Spend a week brainstorming ways to solve modern problems using sci-fi concepts.",
        "Write a series of social media posts as if you were living in the future.",
        "Record a podcast about your favorite sci-fi concepts or themes.",
        "Create a poster for a fictional intergalactic event or festival.",
        "Write a manifesto for a futuristic utopia you'd like to create.",
        "Draw a before-and-after image showing Earth now versus in 500 years.",
        "Develop a pitch for a sci-fi TV show and write the pilot script.",
        "Challenge yourself to make a sci-fi themed music track or soundscape.",
        "Imagine and write about what a futuristic theme park would be like.",
        "Create a YouTube-style tutorial for using a fictional piece of future tech.",
        "Research current NASA projects and write about what excites you most."
    ]
}
